spring:
  application:
    name: Hotel-Management
  datasource:
    url: jdbc:mysql://localhost:3306/hotelManage
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#   profiles:
#     active:
#       - "dev"

aws:
  s3:
    access:
      key: AKIAZ7SAK3YFYV3YOVGV
    secret:
      key: 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
